/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from "workbox-precaching";
import { clientsClaim } from "workbox-core";

declare const self: ServiceWorkerGlobalScope;

// Activate new service worker versions immediately upon installation
self.skipWaiting();
clientsClaim();

// Listen for explicit update trigger messages
self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});

// Clean up outdated caches automatically
cleanupOutdatedCaches();

// Precache all assets generated by Vite build
precacheAndRoute(self.__WB_MANIFEST || []);

// Helper to resolve absolute URLs for icons/images in service worker background thread
function getAbsoluteUrl(path?: string): string | undefined {
  if (!path) return undefined;
  if (path.startsWith("http://") || path.startsWith("https://") || path.startsWith("data:")) {
    return path;
  }
  try {
    return new URL(path, self.location.origin).href;
  } catch (e) {
    return path;
  }
}

// Fallback image urls using uploaded/copied brand icons
const DEFAULT_ICON = getAbsoluteUrl("/pwa_icon_192.png") || "/pwa_icon_192.png";
const DEFAULT_BADGE = getAbsoluteUrl("/pwa_icon_192.png") || "/pwa_icon_192.png";

/**
 * Handle incoming Push Notifications (Runs in background even when app/tab is closed)
 */
self.addEventListener("push", (event) => {
  console.log("[SW PUSH RECEIVED]", event);

  let title = "TaxiApp Notification 🚀";
  let notificationOptions: any = {
    body: "You have a new update.",
    icon: DEFAULT_ICON,
    badge: DEFAULT_BADGE,
    vibrate: [300, 100, 300, 100, 300],
    tag: `taxiapp-push-${Date.now()}`,
    renotify: true,
    requireInteraction: true,
    data: { url: "/" }
  };

  if (event.data) {
    try {
      const data = event.data.json();
      console.log("[SW] Decoded Push Notification payload:", data);

      const notif = data.notification || {};
      const customData = data.data || {};
      
      title = notif.title || customData.title || data.title || "TaxiApp Notification 🚀";

      notificationOptions = {
        body: notif.body || customData.body || data.body || "You have a new update.",
        icon: notif.icon ? getAbsoluteUrl(notif.icon) : (customData.icon ? getAbsoluteUrl(customData.icon) : DEFAULT_ICON),
        badge: notif.badge ? getAbsoluteUrl(notif.badge) : (customData.badge ? getAbsoluteUrl(customData.badge) : DEFAULT_BADGE),
        image: notif.image ? getAbsoluteUrl(notif.image) : (customData.image ? getAbsoluteUrl(customData.image) : undefined),
        vibrate: notif.vibrate || customData.vibrate || [300, 100, 300, 100, 300],
        tag: notif.tag || customData.tag || customData.id || data.id || `taxiapp-push-${Date.now()}`,
        renotify: true,
        requireInteraction: true,
        data: {
          url: customData.url || notif.click_action || data.url || "/",
          actionUrl: customData.actionUrl || customData.url || data.actionUrl || data.url || "/",
          ...customData
        },
        actions: (customData.actionLabel || notif.actions) ? (
          notif.actions || [
            {
              action: "primary_action",
              title: customData.actionLabel || "Open App",
              icon: DEFAULT_ICON
            }
          ]
        ) : undefined
      };
    } catch (err: any) {
      console.warn("[SW] Parsing push data failed, fallback to raw text:", err.message);
      const rawText = event.data.text();
      if (rawText) {
        notificationOptions.body = rawText;
      }
    }
  }

  // Keep service worker alive while native notification is displayed to lock screen/status bar
  event.waitUntil(
    self.registration.showNotification(title, notificationOptions).catch((err) => {
      console.error("[SW SHOW NOTIFICATION ERROR]", err);
    })
  );
});

/**
 * Handle Notification Clicks (Standard redirects and Action buttons)
 */
self.addEventListener("notificationclick", (event) => {
  const notification = event.notification;
  const action = event.action; // 'primary_action' etc.
  const nData = notification.data || {};

  console.log(`[SW] Notification clicked! Action: "${action}", Data:`, nData);

  // Close the clicked notification immediately
  notification.close();

  // Determine destination URL
  let targetUrl = nData.url || "/";
  if (action === "primary_action" && nData.actionUrl) {
    targetUrl = nData.actionUrl;
  }

  // Handle opening or focusing a window matching our scope
  const urlToOpen = new URL(targetUrl, self.location.origin).href;

  event.waitUntil(
    self.clients.matchAll({
      type: "window",
      includeUncontrolled: true
    }).then((windowClients) => {
      // Look for a client window that is already open at any page
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i];
        if ("focus" in client) {
          // Send navigation command to the open tab
          return client.navigate(urlToOpen).then((navigatedClient) => {
            if (navigatedClient) {
              return navigatedClient.focus();
            }
            return client.focus();
          });
        }
      }
      
      // If no window is open, open a new one
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});
